version: '3'
services:

    apache:
        build: .docker/apache
        container_name: sf_apache
        ports:
          - 80:80
        volumes:
          - /home/virtua/sites/studia/video-rental/.docker/config/vhosts:/etc/apache2/sites-enabled
          - /home/virtua/sites/studia/video-rental/app:/home/wwwroot/sf
        depends_on:
          - php

    mysql:
        image: mysql
        ports:
          - 3307:3306
        command: " --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0"
        container_name: sf_mysql
        volumes:
            - /home/virtua/sites/studia/video-rental/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf
            MYSQL_USER: sf
            MYSQL_PASSWORD: sf

    php:
        build: .docker/php
        container_name: sf_php
        volumes:
          - /home/virtua/sites/studia/video-rental/app:/home/wwwroot/sf
        environment:
          - maildev_host=sf_maildev
        depends_on:
          - maildev
          - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: sf_maildev
        ports:
          - 8001:8000
